language: java

jdk:
  - oraclejdk8

sudo: required

addons:
  apt:
    packages:
      - jq

script:
  - build_head=$(git rev-parse HEAD)
  - echo $echo_header
  - echo $TRAVIS_BRANCH
  - echo "hello"